### ISSUE TITLE
Test runner url is incorrect

### ISSUE THREAD

**Issue by NoahTheDuke** [pangloss/pattern#23]
Hey Darrick!

A couple months ago you updated deps and changed the url for Cognitect's `test-runner`. You also changed the url, which is now incorrect. It should have stayed `cognitect-labs/test-runner`.

https://github.com/pangloss/pattern/blob/79cc57792fcb6b72d9ad9036ad29c7fca7e85ca3/deps.edn#L25

**Comment by pangloss** [comment]
Oh, that's weird! Thanks for letting me know.

I've gradually accumulated a bunch of global aliases that I normally use for test watchers and runners. I don't think I've run this alias for ages! Anyway, I've fixed it and it works fine now!
