### ISSUE TITLE
Question: work duplication in evaluation by substitution

### ISSUE THREAD

**Issue by bsless** [pangloss/pattern#3]
A problem which generally exists in implementation of lazy evaluation by substitution is that of work duplication. By if we substitute unconditionally, we might end up returning a closure which contains a computation which could have been computed once before being close over, which might be called many times.
The GHC uses a [combination of strategies and heuristics](https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/compiler/core-to-core-pipeline), including just not inlining inside closures 
There is also theoretical work on [optimal implementation](https://www.amazon.com/Implementation-Functional-Programming-Languages-Theoretical/dp/0521621127) and [sample implementations](http://pauillac.inria.fr/~levy/confer-2/ppr1/node80.html) which work by graph reduction.

Does Pattern have any facilities to address this issue optimally, or would a user have to go for the same heuristics as the Haskell compiler does?

Thanks

**Comment by pangloss** [comment]
I'm not sure if I fully understand this question but I'll try to answer. 

Pattern isn't an interpreter that comes with any specific set of semantics for evaluation of a program, rather it's a toolset that you can use to do bespoke pattern matching and substitution on a wide range of input data types. That seems to indicate to me that the problem you're describing doesn't apply.

I think of Pattern as more akin to an extremely powerful macro expander than as an alternative to the eval/apply loop in an interpreter. In that mode, I think the concerns about work duplication don't apply. Rather, it's up to the creator of the rules to move code to the most optimal place depending on the semantics of the language being expanded.

Regarding unconditional substitutions. When a rule matches, you are able to use the full power of Clojure within the rule body to decide what to do. You may return a form that you know may be further transformed or, if you have all of the context you need, return a form that is in its final form. 

You have good control over when expansions take place, too. With the `directed` matcher you specify that per-rule, or with other rule combinators you are in full control, may walk the tree prewalk or postwalk, or not descend it at all, iterated or not.

**Comment by bsless** [comment]
I'll explain a bit what motivates this question; I have a general interest in performance and one of the unexplored areas in Clojure's performance is optimization during compilation by partial evaluation.
A good example is `(get-in m [a b c])`. Even if the components of the vector are not known at compile time, you can 100% unroll it to `(-> m (get a) (get b) (get c))`
That's at a base level.
The way to do it is by inlining (e.g. substitution) and partial evaluation (`(if (seq [a b c]) ,,,)` always takes the True branch)
Using a pattern matching engine like this library, it is possible to define the semantics of lambda calculus and then just "Eval" the code until you reach a fixed point, where you'd hand it off to Clojure's compiler.

The difficulty is that in evaluation by substitution you can duplicate work:

```clojure
(defn foo [x] (fn [y] (+ x y)))
(map (foo (expensive-computation)) xs)
```
In applicative order evaluation, `(expensive-computation)` will run once. In evaluation by substitution, it will be closed over and the emitted code will run it for every x in xs.

The two approaches to solve this are either:
- don't substitute expressions in closures
- use optimal graph reduction algorithms (which are complicated)

The thrust of the question is whether the library has any facilities to help avoid this particular problem or if I use it for compilation I need to rely on the same heuristics as the GHC does, for example.

**Comment by pangloss** [comment]
You're right that the partial evaluations you describe here can be done very neatly with this library. 

Unfortunately I don't have anything in the library which will automatically solve the problem you're describing. It's likely that the heuristics used by GHC are highly tuned and battle tested, so sound like a good place to look.

**Comment by pangloss** [comment]
Closing, but please feel free to reopen.
